services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cursos_online
      MYSQL_ROOT_PASSWORD: Semsenha13
    volumes:
      - mysql-data:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql-data:
